### ISSUE TITLE
security / authentication?

### ISSUE THREAD

**Issue by psifertex** [JeffreyDavidsz/VICREO-Listener#73]
Unless I'm missing something this service is a giant un-authenticated remote-control session. It would be nice if there was some sort of authentication or encryption possible as without it, it's trivial to turn this into a remote exploit.

In fact, a quick check on [shodan](https://www.shodan.io/) shows a number of folks running VICREO-Listener on a default port on the internet without any firewall at all. That's really bad!

**Comment by JeffreyDavidsz** [comment]
Hi Jordan, your not missing something, this tool was created because an other tool didn't work anymore. I'm rewriting the tool as we speak and password protected access will be one of the features. Unfortunately its a hobby thing and I'm a bit packed with work. So I could not tell you what the timeframe will be.

**Comment by psifertex** [comment]
No worries at all -- in the meantime I think just a short update in the readme would be helpful to warn users so they can better understand the risks! I'd be happy to help with a PR unless you'd rather include that language.

**Comment by JeffreyDavidsz** [comment]
Sending to the listener is now password protected (if needed), enter a password and after that it will only accept that (hashed) password.
