### ISSUE TITLE
Password function doesn't work with Companion

### ISSUE THREAD

**Issue by russcinramona** [JeffreyDavidsz/VICREO-Listener#86]
I just upgraded to VICREO 3.0.0 and am using it with Companion 2.1.3 (latest available version).  There is a password option added to 3.0.0 that seems to break communications with Companion.  I tried no password in the VICREO console as well as entering a password.  VICREO connects with Companion but any commands generate a 'no password provided' message in the log.  Looking at the code, it looks like there is no check for whether password is an empty string and runs md5() on it.  This may not behave as expected.
![image](https://user-images.githubusercontent.com/35514039/126046550-557a5509-6b42-4497-932b-117d72da23fb.png)

**Comment by JeffreyDavidsz** [comment]
As mentioned, you would need a beta build from Companion and select version 3.0.0 there. If you don't see the option, the version of companion is too old.

**Comment by russcinramona** [comment]
Mentioned where?  
![image](https://user-images.githubusercontent.com/35514039/126046631-2128a0a9-5bb4-4b1d-8de6-cdfc7fcb0b1d.png)

**Comment by JeffreyDavidsz** [comment]
See log output

**Comment by russcinramona** [comment]
Here is the full log output: 
11:26:06 no password provided, make sure you send one
11:26:06 received: {"key":"F6","type":"press","modifiers":[]}
11:26:05 no password provided, make sure you send one
11:26:05 received: {"key":"tab","type":"press","modifiers":["alt"]}
11:23:55 no password provided, make sure you send one
11:23:55 received: {"type":"file","path":"C:/Users/RussC/Documents/2020 Winners.xlsx"}
11:22:43 connected
11:21:48 Found IPv4 address: 192.168.1.81
11:21:48 Found IPv4 address: 192.168.1.239

**Comment by russcinramona** [comment]
BTW, thanks for your quick responses!  I'm just trying to understand how I missed it.

**Comment by JeffreyDavidsz** [comment]
no password provided, make sure you send one. 
Companion 2.1.3 doesn't send a password with it. An empty password is allowed also as the MD5 hash will give a famous result. But a `"password": "xxx"` must be send

**Comment by JeffreyDavidsz** [comment]
I've changed the release description

**Comment by russcinramona** [comment]
Okay thanks.  You might consider a change to VICREO that would increase compatibility.  If no "password": "xxx" is sent, default to empty string for the incoming password, then compare against the VICREO password (either empty or set).  If a VICREO password is set and no password provided, the command would fail as expected.  If both are empty (or the passwords match) the command succeeds.  This would make VICREO compatible with older non-password clients.

**Comment by JeffreyDavidsz** [comment]
Good suggestion, I've added it to 3.0.1

**Comment by franklyray** [comment]
Jeffrey. For the non-tech person on Windows, I am successfully using 2.1.0. 

I don't understand how to deal with the 3.0 when it relates to passwords. I am not comfortable doing anything to a program that requires coding. 

I use Companion and SteamDeck for BMD ATEM Mini Extreme. I have the feeling I should wait a while? Appreciate your suggestion.

**Comment by JeffreyDavidsz** [comment]
You could wait for 3.0.1 release then when sending no password it's ok. Or you can upgrade companion to a latest build and it will work with 3.0.0.
I'll release 3.0.1 soon, just need to do test and sign the windows version manually

**Comment by JeffreyDavidsz** [comment]
3.0.1 released

**Comment by russcinramona** [comment]
I just installed VICREO-Listener 3.0.1 on Windows 10 and tried it with Companion 2.1.3 (latest release, non-beta version, no password support).  I still receive "Wrong password" and no password provided messages.  I am using an empty password value in the VICREO password text box (see image).  Should this configuration work in 3.0.1?
![image](https://user-images.githubusercontent.com/35514039/126230451-2a1f9054-a617-42f1-9e31-e69330d9bffd.png)

**Comment by russcinramona** [comment]
I just looked at the code and it looks like you need to do a data.password check in processIncomingData().  Here is your code:
`function processIncomingData(data) {
	mainWindow.webContents.send('log', 'received: ' + JSON.stringify(data))
	if(!data.password) {
		mainWindow.webContents.send('log', 'no password provided, make sure you send one {"password": "MD5(xxx)"}')
		if(password != "") {
			return
		}
	}
	if (data.password == md5(password)) {
`
I think you need to add something like (I'm a C programmer, not js, so apologies)
`
	if(password == "") {
		data.password = ""		// defines data.password and sets it to match VICREO password only if it is empty string
	}
	if(!data.password) {
		mainWindow.webContents.send('log', 'no password provided, make sure you send one {"password": "MD5(xxx)"}')
		if(password != "") {
			return
		}
	}`

Hope that makes sense.
-Russ

**Comment by JeffreyDavidsz** [comment]
The login messages are wrong indeed. I'll check it with a bit more time. Thank you for testing

**Comment by JeffreyDavidsz** [comment]
Should be working now, I'll try to update the builds

**Comment by q1pt2rx** [comment]
Hello, I want to thank you for this software, it works perfectly for my needs.

However, since you've committed the necessary changes to fix the password issue you haven't rebuilt it as a release distributable.

Thankfully I was able to figure out how to build it from the source code, and I learned a lot in the process; it now works exactly as expected.

I just wanted to gently remind you that for the majority of those hoping to use vicreo with bitfocus' companion still won't be able to until it has been rebuilt.

Cheers

**Comment by JeffreyDavidsz** [comment]
Hi Rocco,

I think I forgot to upload the windows version? I’ll do that, thanks for your feedback!

Kind regards,

***@***.***D766D9.C1D18870]
[logo143x59]

Van: Rocco Ruscitti ***@***.***>
Verzonden: zondag 25 juli 2021 16:21
Aan: JeffreyDavidsz/VICREO-Listener ***@***.***>
CC: Jeffrey Davidsz ***@***.***>; State change ***@***.***>
Onderwerp: Re: [JeffreyDavidsz/VICREO-Listener] Password function doesn't work with Companion (#86)


Hello, I want to thank you for this software, it works perfectly for my needs.

However, since you've committed the necessary changes to fix the password issue you haven't rebuilt it as a release distributable.

Thankfully I was able to figure out how to build it from the source code, and I learned a lot in the process; it now works exactly as expected.

I just wanted to gently remind you that for the majority of those hoping to use vicreo with bitfocus' companion still won't be able to until it has been rebuilt.

Cheers
