### ISSUE TITLE
Can I change the port by myself?

### ISSUE THREAD

**Issue by houtacheng** [JeffreyDavidsz/VICREO-Listener#9]
like 1002

**Comment by JeffreyDavidsz** [comment]
This could be made yes, can you give an example why the standard port doesn't work for you?

**Comment by houtacheng** [comment]
Because at the same time i use another program : octopus listen (http://noismada.com/)
this program's port is 1001 too

**Comment by JeffreyDavidsz** [comment]
The reason I build VICREO-Listener was that there wasn't any support coming from that author. Both programs do the same. Don't use them at the same time, just choose for 1. Or did I miss a functionality that octopus has and VICREO doesn't?

**Comment by houtacheng** [comment]
VICREO supports most of the features, but unfortunately there is no support for launching Keynote and launching PPT.
<img width="348" alt="001" src="https://user-images.githubusercontent.com/25832189/56466230-526c6c80-6441-11e9-898f-3e31c6d7deae.png">

**Comment by JeffreyDavidsz** [comment]
Use the keys you would use on your keyboard. Windows PowerPoint = F5 for example

**Comment by ShawnMiller510** [comment]
Sorry to bump an old thread - I want to start using Vicreo instead of Octopus (because, as mentioned above, the author of Octopus Listener abandoned the project years ago) but I'm having trouble replicating the "PPT goto slide (nr)" function from Octopus. 

It seems to work in Keynote, but it never registers the numerical input when in PPT. Instead of jumping to slide 1 or slide 20, it only advances one slide. Any suggestions how I should be trying to build this? I'm using Companion and a Stream Deck.

Thanks

**Comment by JeffreyDavidsz** [comment]
You could try this, single key `1` little delay of 30ms, then second command `enter`

**Comment by houtacheng** [comment]
go to pages 12：
![image](https://user-images.githubusercontent.com/25832189/65715996-a6c0eb80-e074-11e9-8f32-cfcc515ef633.png)

**Comment by ShawnMiller510** [comment]
Thanks for the quick responses - I tried both these methods and unfortunately it is still just advancing the slides rather than going to a specific slide.

For reference I'm using:
VICREO_Listener_OSX (most recent version)
Companion v1.4.0 (backport-b402e70-1559
PPT Version 16.18 (181014) - Office 365 Subscription running on
MacBook Pro 2017 macOS Mojave Version 10.14.6

Again, it seems to work as expected when I'm navigating slides in Keynote (or even in Notepad or Word, it's typing the numbers and hitting return) but PPT is not responding as it should.

When I have the opportunity, I'll try it on a few other machines.

**Comment by JeffreyDavidsz** [comment]
Just to check, on the PPT machine use the keyboard and type it there. When the focus is of the program it doesn't work. So what happens when you type it directly? On a windows machine you can also use irisdown remote control as alternative

**Comment by ShawnMiller510** [comment]
Typing in a number and hitting return on the keyboard works as expected - jumping directly to that slide. 

As far as I can tell the focus is on the program, I'm using Vicreo to open the .pptx file, to start the presentation, and to advance slides. This is the only command that doesn't seem to be registering, which is baffling me. 

In about 15 minutes I can test it on another MacBook and possibly a Windows machine too. (I'm working an event right now and the other computers are running videos and speaker timers at the moment.)

**Comment by JeffreyDavidsz** [comment]
How many delay did you put in between, seems like only the enter arrives?

**Comment by ShawnMiller510** [comment]
I tried a few different delays, everything from 10ms to 500ms. I even tried to enter '1' on key down and 'enter' on key up - same result, only the enter arrives for some reason.

Just tried it with Powerpoint on a different MacBook with the same result. Trying to hunt down an available Windows machine now.

**Comment by ShawnMiller510** [comment]
Yeah, it works flawlessly on PowerPoint on a PC. It seems to be a Mac issue. I'll continue looking for a workaround.

**Comment by JeffreyDavidsz** [comment]
I've check the above myself and it works, the numbers with the enter don't work. Anywhere outside powerpoint it works. need to look into powerpoint for mac

**Comment by JeffreyDavidsz** [comment]
@houtacheng please test the latest pre-release for the portnumber change. Haven't test anything on OSX yet only on windows
